### ISSUE TITLE
You're using dpANS3, why not dpANS3R instead? Do you know of a reliable source for it?

### ISSUE THREAD

**Issue by Hexstream** [robert-strandh/Well-Specified-Common-Lisp#1]
Hello,

Based on the knowledge I've gained from [this issue](https://github.com/xach/dpans/issues/1), what you're using here is "dpANS3" (11 May 1994).

There is also a "dpANS3R" (12 august 1994) floating around on the internet, which is a slightly later version, with fairly inconsequential changes.

But I was wondering if there was a specific reason that you (and other people) are using dpANS3 instead of dpANS3R. I was also wondering if someone knows of a reliable, "canonical" source for dpANS3R that is guaranteed to be the unmodified original, and indeed if there is no known reliable source for it then it's understandable why people would use dpANS3 instead of dpANS3R.

**Comment by robert-strandh** [comment]
Hello,

I guess I was unaware of (or forgot about) dpANS3R.

I remember having a hard time finding what I did find (dpANS3), so
when I eventually did, I downloaded it immediately.

So, no, I don't have any particular reason for not using R.

**Comment by Hexstream** [comment]
Ok, thanks. That answers my question, so I guess I'll close this.
