### ISSUE TITLE
is:issue is:open The building instructions

### ISSUE THREAD

**Issue by hww** [robert-strandh/Well-Specified-Common-Lisp#8]
Would be nice to add a short instruction how to build. 
Right now, executing `make` files from `LaTex` folder got `error` because can't find files in `dpANS` folder. So what should I do?
![image](https://user-images.githubusercontent.com/773541/180996866-c115b4f8-9449-4429-9731-feede266706f.png)

**Comment by robert-strandh** [comment]
The main repository for WSCL is this one now: https://github.com/s-expressionists/wscl
